### ISSUE TITLE
README wallpaper

### ISSUE THREAD

**Issue by r33int** [petrroll/PowerSwitcher#12]
Hi, could you share the wallpaper you used in the first screenshot of the README.md file? Thanks
![image](https://user-images.githubusercontent.com/22567851/35811841-cdc722ec-0a8f-11e8-83ad-c318144c629d.png)

**Comment by petrroll** [comment]
Sure, it's a picture of Albanian mountains :). Not very high-res as my mobile phone doesn't have the best camera.
![dsc_0242](https://user-images.githubusercontent.com/1764721/35812543-92edee56-0a91-11e8-9c3e-51d68e530f09.JPG)
