### ISSUE TITLE
Scroll wheel doesn't work

### ISSUE THREAD

**Issue by LongKick64** [petrroll/PowerSwitcher#3]
If you create a lot of power schemes, the mouse scroll wheel will not work in the flyout panel: http://take.ms/XHyNW

**Comment by petrroll** [comment]
Fixed, update should be up in a few days.

**Comment by LongKick64** [comment]
Also, when the list is large keys Pg Up and Pg Dn on the keyboard do not work correctly. They omit to the end and at the top of the list, respectively.
