### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by ArtIsResistance** [petrroll/PowerSwitcher#5]
Error while updating from Store (0x80070216). Before that worked like a charm.
OS: Windows 10 AU 1607 (Build 14393.953)

**Comment by petrroll** [comment]
It seems I have the same problem locally. Uninstalling the old version and installing the new one helps, though. I'll try to look into it a bit more but since I didn't change anything about the packaging in the last update it's probably a Microsoft's bug.

**Comment by petrroll** [comment]
##Events:

AppxXDeployment/Operational:
`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-AppXDeployment" Guid="{8127F6D4-59F9-4ABF-8952-3E3A02073D5F}" /> 
  <EventID>301</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>4</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x4000400000010000</Keywords> 
  <TimeCreated SystemTime="2017-03-20T10:43:04.668336500Z" /> 
  <EventRecordID>2439</EventRecordID> 
  <Correlation ActivityID="{2B6B27F8-9FCA-0000-1C0C-6E2BCA9FD201}" /> 
  <Execution ProcessID="6588" ThreadID="14668" /> 
  <Channel>Microsoft-Windows-AppXDeployment/Operational</Channel> 
  <Computer>Petrroll-PC</Computer> 
  <Security UserID="S-1-5-21-369683384-1778959002-783717580-1001" /> 
  </System>
- <EventData>
  <Data Name="FileName">RuntimeBroker.exe</Data> 
  </EventData>
  </Event>`

**Comment by petrroll** [comment]
Windows events: https://1drv.ms/f/s!Ak2iL3P_ifT3hOoQDYsTkBDXMg_bHQ

**Comment by petrroll** [comment]
Building a new version (with minimal differences) didn't help.

**Comment by petrroll** [comment]
@ArtIsResistance Just FIY, the absolutely newest version doesn't contain any extremely useful bugfixes so feel free to use the old version in the meantime :).

**Comment by petrroll** [comment]
In case some Microsoft people come here to investigate:
- The script that [invokes packaging](https://github.com/petrroll/PowerSwitcher/blob/master/PowerSwitcher.Appx/PackageScript.bat)
- [AppX manifest](https://github.com/petrroll/PowerSwitcher/blob/master/PowerSwitcher.Appx/AppxManifest.xml)

**Comment by vladimp** [comment]
Thanks for reporting the issue, it is a known issue/regression, we have the fix and will release it in our next patch. 

Thanks,
Vlad

**Comment by LongKick64** [comment]
I also could not upgrade to version 0.4.4.0. Reset it and updated successfully! http://take.ms/H8TwB
