### ISSUE TITLE
Is there no release?

### ISSUE THREAD

**Issue by spin360** [petrroll/PowerSwitcher#8]
Hello there!

I just wanted to try this, as I've been using another program for that, but there is no release to download. I'm not a very advanced github user, so I am not sure where I should download it.

Thanks
Alex

**Comment by petrroll** [comment]
Hi! The app is available here: https://www.microsoft.com/en-us/store/p/powerplanswitcher/9nblggh556l3

**Comment by spin360** [comment]
Oooh, thanks!
Time to use the Windows Store for the first time lol

**Comment by petrroll** [comment]
It's not as bad as some people say  and there are actually some useful apps such as Spotify, InkScape, InfranView, etc now :).

**Comment by petrroll** [comment]
Related: #17
