### ISSUE TITLE
The current version of 16299.15/rs 3 is not available for this application

### ISSUE THREAD

**Issue by ghsssss** [petrroll/PowerSwitcher#9]
The current version of 16299.15/rs 3 is not available for this application

**Comment by dspjm** [comment]
Same to me

**Comment by ghsssss** [comment]
I found that the app was off the shelf

**Comment by dspjm** [comment]
not to me, i can still find it in the store, but there is only the balance power plan.

**Comment by petrroll** [comment]
Yeah, I've noticed that too. Unfortunately there's nothing I can do about
that. Microsoft simply deleted the old schemas during update process. You
can always add the old schemas manually, thought.
